### ISSUE TITLE
init_secrets creates master.key then returns an error from aes.py (self.key is None)

### ISSUE THREAD

**Issue by mithi** [nzaillian/django-encrypted-secrets#8] opened 2020-03-07 08:59 UTC
Running 
```
 ./manage.py init_secrets
```
the first time generates `master.key` and `secrets.yml.enc`  but produces the following 
error below. It could not find the key (`key is None`). Running the same command the second time (after running it the first time) doesn't return an error, which I assume it uses the `master.key` it had generated when the command was run the first time. 

```
 ➜ ./manage.py init_secrets     
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    main()
  File "./manage.py", line 21, in main
    load_secrets()
  ./env/lib/python3.7/site-packages/encrypted_secrets/__init__.py", line 74, in load_secrets
    SecretsManager.load(**kwargs)
  ./env/lib/python3.7/site-packages/encrypted_secrets/__init__.py", line 20, in load
    cls.load_from_yaml(encrypted_secrets_file_path, key)
 ./env/lib/python3.7/site-packages/encrypted_secrets/__init__.py", line 26, in load_from_yaml
    secrets_yaml = read_secrets(encrypted_secrets_file_path, key)
  ./env/lib/python3.7/site-packages/encrypted_secrets/util.py", line 37, in read_secrets
    cipher = AESCipher(message, key)
  ./env/lib/python3.7/site-packages/encrypted_secrets/crypto/aes.py", line 10, in __init__
    self.key = sha256(key.encode()).digest()[:32]
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by vordankarmir** [comment] 2020-05-31 07:04
Hey @mithi I have got this error too, have you found a solution?

**Comment by mithi** [comment] 2020-05-31 10:16
unfortunately i have decided not to use this anymore

**Comment by vordankarmir** [comment] 2020-05-31 11:02
Hey @mithi, btw the problem is that your master.key and secrets.yml.enc must be in the project root directory, after that you must run `python ./manage.py edit_secrets` and it will open editor where you must write credentials to encrypt.

**Comment by mithi** [comment] 2020-05-31 11:06
thanks. it’s a little fuzzy but i remember that i was able to iron out a
few bugs i encountered along the way but then there was a point that
decided to use the traditional environment variables as what i usually see
in other similar but more polished projects.

Thanks. I should close that issue now.

**Comment by nzaillian** [comment] 2020-06-02 03:35
Sorry, I have been away literally on an island the last several months and missed a whole load of notifications, but finally saw this one just now. I fixed this in https://github.com/nzaillian/django-encrypted-secrets/commit/d74436fe1db66463a13db2f4eacbad703af36c2e (package v.0.9.9 on PyPi). I will certainly try to find a maintainer of this project longer term as I no longer work in Django much, however I will add some notes to the README on development workflow at the least. Thank you

**Comment by nzaillian** [comment] 2020-06-02 03:35
(addressed in https://github.com/nzaillian/django-encrypted-secrets/commit/d74436fe1db66463a13db2f4eacbad703af36c2e, v0.9.9 on [PyPi](https://pypi.org/project/django-encrypted-secrets/))

**Closed as completed by nzaillian** 2020-06-02 03:35 UTC
